### PR TITLE
Rebranded copy, assets and links with K+C branding

### PR DESCRIPTION
**Pull request by jsanderson44**
Updated:
* Readme copy and links
* Test json copy
* Assets and fonts

### CODE REVIEW

**Comment by jsanderson44** [comment]
Lots of changes made to https://github.com/theappbusiness/engineering-challenge/pull/6/files#diff-346f686c82fd60184f42e34280bfd0f4 (which doesnt render by default due to its size)

**Review by nickhegarty — COMMENTED** [review]
Looks good!

**Comment by jsanderson44** [comment]
> Looks good, should we include a note about the font and logo assets that could be useful in the "Putting your stamp on it" section?

@nickhegarty I think we actually deliberately left that out to see how proactive and thorough people were.

**Comment by nickhegarty** [comment]
> > Looks good, should we include a note about the font and logo assets that could be useful in the "Putting your stamp on it" section?
> 
> @nickhegarty I think we actually deliberately left that out to see how proactive and thorough people were.

Great, approving now. (and deleting my comments 😄 )

**Review by nickhegarty — APPROVED** [review]
Looks good to me!

**Pull request merged**
